### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [ACBSmith/george-bernard-shaw_the-man-of-destiny#1]
- [ ] modernize-spelling changes Buonaparte to Bonaparte. Did you leave this intentionally?
- [x] Unsemanticated italics: a couple instances of `<i>` that should be` <em>`
- [ ] In the long description, is the name of the collection not "Plays: Pleasant and Unpleasant"? 
- [x] Replace quotes around L'Empereur with French tagged italics
- [x] Add italics around "En avant, mes enfants!"
- [x] I would modernize lappel -> lapel

**Comment by ACBSmith** [comment]
Buonaparte is left intentionally, as it describes a different pronunciation. Both spellings are present.
The first collection it was published in was _Plays Pleasant_; there was another volume called _Plays Unpleasant_ and in later editions the two collections were published in one larger volume.
